/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package employeecustomermanagement;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author nepom
 */
public class AddUpdatePersonIFrame extends javax.swing.JInternalFrame {

    private String currentAction;
    private int currentIDSelected;

    /**
     * Creates new form AddUpdatePersonIFrame
     */
    public AddUpdatePersonIFrame() {
        initComponents();
        this.currentAction = "Add";
        this.PersonIDTextField.setEnabled(false);
        this.SelectButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonIDTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SelectButton = new javax.swing.JButton();
        AddUpdatePersonTabbedPane = new javax.swing.JTabbedPane();
        CustomerTab = new javax.swing.JPanel();
        CustomerAddressTextField = new javax.swing.JTextField();
        CustomerTelephoneTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CustomerNameTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CustomerGenderComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        CustomerDOBDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CustomerLicenseNumberTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CustomerLicenseExpiryDatePicker = new org.jdesktop.swingx.JXDatePicker();
        CustomerLicenseTypeComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmployeeNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmployeeGenderComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        EmployeeDOBDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        EmployeeAddressTextField = new javax.swing.JTextField();
        EmployeeTelephoneTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EmployeePhoneExtensionTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EmployeeUsernameTextField = new javax.swing.JTextField();
        EmployeePasswordTextField = new javax.swing.JTextField();
        EmployeeRoleComboBox = new javax.swing.JComboBox<>();
        ActionComboBox = new javax.swing.JComboBox<>();
        ActionButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 360));

        PersonIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonIDTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        SelectButton.setText("Select");
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });

        CustomerAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerAddressTextFieldActionPerformed(evt);
            }
        });

        CustomerTelephoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerTelephoneTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Name");

        jLabel12.setText("Telephone");

        CustomerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Gender");

        CustomerGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female", "Other" }));
        CustomerGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerGenderComboBoxActionPerformed(evt);
            }
        });

        jLabel15.setText("Date of Birth");

        jLabel16.setText("Address");

        jLabel13.setText("License Number");

        CustomerLicenseNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerLicenseNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("License Type");

        jLabel18.setText("License Expiry Date");

        CustomerLicenseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Learner", "Restricted", "Full" }));
        CustomerLicenseTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerLicenseTypeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerTabLayout = new javax.swing.GroupLayout(CustomerTab);
        CustomerTab.setLayout(CustomerTabLayout);
        CustomerTabLayout.setHorizontalGroup(
            CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerTabLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerDOBDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerTelephoneTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerLicenseTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 154, Short.MAX_VALUE)
                    .addComponent(CustomerLicenseNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CustomerLicenseExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        CustomerTabLayout.setVerticalGroup(
            CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(CustomerLicenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CustomerGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(CustomerDOBDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(CustomerLicenseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CustomerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(CustomerLicenseExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CustomerTelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        AddUpdatePersonTabbedPane.addTab("Customer", CustomerTab);

        jLabel1.setText("Name");

        EmployeeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Gender");

        EmployeeGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female", "Other" }));
        EmployeeGenderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeGenderComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Date of Birth");

        jLabel5.setText("Address");

        EmployeeAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeAddressTextFieldActionPerformed(evt);
            }
        });

        EmployeeTelephoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeTelephoneTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Telephone");

        jLabel7.setText("Extension");

        EmployeePhoneExtensionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeePhoneExtensionTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Role");

        jLabel9.setText("Username");

        jLabel10.setText("Password");

        EmployeeRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Manager", "Sales", "Deskfront" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeTelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeePhoneExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeDOBDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeNameTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeePasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(EmployeeUsernameTextField))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(EmployeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(EmployeeGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(EmployeeDOBDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(EmployeeUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(EmployeePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EmployeeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(EmployeeRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EmployeeTelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(EmployeePhoneExtensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        AddUpdatePersonTabbedPane.addTab("Staff", jPanel2);

        ActionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Update" }));
        ActionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionComboBoxActionPerformed(evt);
            }
        });

        ActionButton.setText("Add");
        ActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddUpdatePersonTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PersonIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SelectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ActionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ActionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PersonIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectButton)
                    .addComponent(ActionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddUpdatePersonTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ActionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersonIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonIDTextFieldActionPerformed

    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButtonActionPerformed

        String personIDText = PersonIDTextField.getText();
        int personID;
        if (personIDText.length() == 0) {
            JOptionPane.showMessageDialog(this, "Person ID cannot be empty.",
                    "Empty ID Field", JOptionPane.ERROR_MESSAGE);
            resetAll();

            // Input Validation: ID cannot be any other characters except integer
        } else if (!IndexFrame.isInt(personIDText) || 0 > Integer.parseInt(personIDText)) {
            JOptionPane.showMessageDialog(this, "Please input a valid ID number.",
                    "Invalid ID", JOptionPane.ERROR_MESSAGE);
            resetAll();

            // Proceed to put personID value if no error
        } else {
            personID = Integer.parseInt(personIDText);
            currentIDSelected = personID;
            if (AddUpdatePersonTabbedPane.getSelectedIndex() == 0) {
                boolean customerFound = false;
                for (Customer c : IndexFrame.db.CustomerList) {
                    if (personID == c.getPersonID()) {
                        CustomerNameTextField.setText(c.getName());
                        CustomerGenderComboBox.setSelectedItem(c.getGender());
                        CustomerDOBDatePicker.setDate(c.getDateOfBirth());
                        CustomerAddressTextField.setText(c.getAddress());
                        CustomerTelephoneTextField.setText(c.getTelNumber());
                        CustomerLicenseNumberTextField.setText(c.getLicenseNumber() + "");
                        CustomerLicenseTypeComboBox.setSelectedItem(toTitleCase(c.getLicenseType().toString()));
                        CustomerLicenseExpiryDatePicker.setDate(c.getLicenseExpiryDate());
                        customerFound = true;
                        break;
                    }
                }
                if (!customerFound) {
                    JOptionPane.showMessageDialog(this, "No customer found.",
                    "No Customer Found", JOptionPane.INFORMATION_MESSAGE);
                    PersonIDTextField.setText("");
                }
            } else if (AddUpdatePersonTabbedPane.getSelectedIndex() == 1) {
                boolean employeeFound = false;
                for (Employee e : IndexFrame.db.EmployeeList) {
                    if (personID == e.getPersonID()) {
                        EmployeeNameTextField.setText(e.getName());
                        EmployeeGenderComboBox.setSelectedItem(e.getGender());
                        EmployeeDOBDatePicker.setDate(e.getDateOfBirth());
                        EmployeeAddressTextField.setText(e.getAddress());
                        EmployeeTelephoneTextField.setText(e.getTelNumber());
                        EmployeeRoleComboBox.setSelectedItem(toTitleCase(e.getRole().toString()));
                        EmployeePhoneExtensionTextField.setText(e.getPhoneExt());
                        EmployeeUsernameTextField.setText(e.getUsername());
                        EmployeePasswordTextField.setText(e.getPassword());
                        employeeFound = true;
                        break;
                    }
                }
                if (!employeeFound) {
                    JOptionPane.showMessageDialog(this, "No employee found.",
                    "No Employee Found", JOptionPane.INFORMATION_MESSAGE);
                    PersonIDTextField.setText("");
                }
            }
        }

    }//GEN-LAST:event_SelectButtonActionPerformed

    /*
    Rules:
    - Fields cannot be empty
    - Date of Birth cannot be in the future
    - Customer: License Expiry Date must not be in the past
    - Customer: License Number must be unique
    - Employee: Phone Extension must be unique
     */
    private boolean validateEmployeeData() {
        boolean status = true;
        if ( // No empty field
                EmployeeNameTextField.getText().equals("")
                || EmployeeGenderComboBox.getSelectedIndex() == 0
                || EmployeeDOBDatePicker.getDate() == null
                || EmployeeAddressTextField.getText().equals("")
                || EmployeeTelephoneTextField.getText().equals("")
                || EmployeeRoleComboBox.getSelectedIndex() == 0
                || EmployeePhoneExtensionTextField.getText().equals("")
                || EmployeeUsernameTextField.getText().equals("")
                || EmployeePasswordTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Input fields cannot be empty.",
                    "Empty Fields", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        // Check existing employee by basic person details, phone extension, or username
        for (Employee e : IndexFrame.db.EmployeeList) {
            if (
                EmployeeNameTextField.getText().equals(e.getName())
                && EmployeeGenderComboBox.getSelectedItem().toString().equals(e.getGender())
                && IndexFrame.isSameDate(IndexFrame.CalendarNoHSM(EmployeeDOBDatePicker.getDate()),
                        IndexFrame.CalendarNoHSM(e.getDateOfBirth()))
                && EmployeeAddressTextField.getText().equals(e.getAddress())
                && EmployeeTelephoneTextField.getText().equals(e.getTelNumber())
            ) {
                JOptionPane.showMessageDialog(this, "This employee already exist.",
                    "Existing Employee", JOptionPane.WARNING_MESSAGE);
                return false;
            } else if (e.getPhoneExt().equals(EmployeePhoneExtensionTextField.getText())) {
                JOptionPane.showMessageDialog(this, "Phone extension number must be unique.",
                        "Phone Number Already Registered", JOptionPane.WARNING_MESSAGE);
                status = false;
            } else if (e.getUsername().equals(EmployeeUsernameTextField.getText())) {
                JOptionPane.showMessageDialog(this, "Username " + e.getUsername() + " is already in use.",
                        "Username Already Registered", JOptionPane.WARNING_MESSAGE);
                status = false;
            }
        }
        
        if (EmployeeDOBDatePicker.getDate().after(new Date())) {
            JOptionPane.showMessageDialog(this, "Date of Birth must not be in the future.",
                    "Invalid Date of Birth", JOptionPane.ERROR_MESSAGE);
            status = false;
        }

        if (!IndexFrame.isInt(EmployeePhoneExtensionTextField.getText())) {
            JOptionPane.showMessageDialog(this, "Phone Extension Number must be a whole number .",
                    "Invalid Phone Extension", JOptionPane.ERROR_MESSAGE);
            status = false;
        }
        
        return status;
    }

    private boolean validateCustomerData() {
        boolean status = true;
        if ( // No empty field
            CustomerNameTextField.getText().equals("")
            || CustomerGenderComboBox.getSelectedIndex() == 0
            || CustomerDOBDatePicker.getDate() == null
            || CustomerAddressTextField.getText().equals("")
            || CustomerTelephoneTextField.getText().equals("")
            || CustomerLicenseNumberTextField.getText().equals("")
            || CustomerLicenseTypeComboBox.getSelectedIndex() == 0
            || CustomerLicenseExpiryDatePicker.getDate() == null
        ) {
            JOptionPane.showMessageDialog(this, "Input fields cannot be empty.",
                    "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        // Check existing customer by basic person details or by license number
        for (Customer c: IndexFrame.db.CustomerList) {
            System.out.println(CustomerNameTextField.getText().equals(c.getName()));
            System.out.println(CustomerGenderComboBox.getSelectedItem().toString().equals(c.getGender()));
            System.out.println(IndexFrame.isSameDate(IndexFrame.CalendarNoHSM(CustomerDOBDatePicker.getDate()),
                    IndexFrame.CalendarNoHSM(c.getDateOfBirth())));
            System.out.println(CustomerAddressTextField.getText().equals(c.getAddress()));
            System.out.println(CustomerTelephoneTextField.getText().equals(c.getTelNumber()));
            
            if (
                CustomerNameTextField.getText().equals(c.getName())
                && CustomerGenderComboBox.getSelectedItem().toString().equals(c.getGender())
                && IndexFrame.isSameDate(IndexFrame.CalendarNoHSM(CustomerDOBDatePicker.getDate()),
                    IndexFrame.CalendarNoHSM(c.getDateOfBirth()))
                && CustomerAddressTextField.getText().equals(c.getAddress())
                && CustomerTelephoneTextField.getText().equals(c.getTelNumber())
            ) {
                JOptionPane.showMessageDialog(this, "This customer already exist.",
                    "Existing Customer", JOptionPane.WARNING_MESSAGE);
                return false;
            } else if ((c.getLicenseNumber()+"").equals(CustomerLicenseNumberTextField.getText())) {
                JOptionPane.showMessageDialog(this, "License number must be unique.",
                        "License Already Registered", JOptionPane.WARNING_MESSAGE);
                status = false;
            }
        }
        
        if (CustomerDOBDatePicker.getDate().after(new Date())) {
            JOptionPane.showMessageDialog(this, "Date of Birth must not be in the future.",
                    "Invalid Date of Birth", JOptionPane.WARNING_MESSAGE);
            status = false;
        }
        if (CustomerLicenseExpiryDatePicker.getDate().before(new Date())) {
            JOptionPane.showMessageDialog(this, "License must not be expired.",
                    "Invalid License Expiry Date", JOptionPane.WARNING_MESSAGE);
            status = false;
        }
        if (!IndexFrame.isInt(CustomerLicenseNumberTextField.getText())) {
            JOptionPane.showMessageDialog(this, "License number must be a whole number.",
                    "Invalid License Number", JOptionPane.WARNING_MESSAGE);
            status = false;
        }
        
        return status;
    }

    private String toTitleCase(String text) {
        String firstLetter = text.substring(0, 1).toUpperCase();
        String theRest = text.substring(1).toLowerCase();
        return firstLetter + theRest;
    }

    private void resetAll() {
        PersonIDTextField.setText("");
        currentIDSelected = 0;
        CustomerNameTextField.setText("");
        CustomerGenderComboBox.setSelectedIndex(0);
        CustomerDOBDatePicker.setDate(null);
        CustomerAddressTextField.setText("");
        CustomerTelephoneTextField.setText("");
        CustomerLicenseNumberTextField.setText("");
        CustomerLicenseTypeComboBox.setSelectedIndex(0);
        CustomerLicenseExpiryDatePicker.setDate(null);
        EmployeeNameTextField.setText("");
        EmployeeGenderComboBox.setSelectedIndex(0);
        EmployeeDOBDatePicker.setDate(null);
        EmployeeAddressTextField.setText("");
        EmployeeTelephoneTextField.setText("");
        EmployeeRoleComboBox.setSelectedIndex(0);
        EmployeePhoneExtensionTextField.setText("");
        EmployeeUsernameTextField.setText("");
        EmployeePasswordTextField.setText("");
    }

    private void EmployeeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeNameTextFieldActionPerformed

    private void EmployeeGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeGenderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeGenderComboBoxActionPerformed

    private void EmployeeAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeAddressTextFieldActionPerformed

    private void EmployeeTelephoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeTelephoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeTelephoneTextFieldActionPerformed

    private void EmployeePhoneExtensionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeePhoneExtensionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeePhoneExtensionTextFieldActionPerformed

    private void CustomerAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerAddressTextFieldActionPerformed

    private void CustomerTelephoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerTelephoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerTelephoneTextFieldActionPerformed

    private void CustomerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameTextFieldActionPerformed

    private void CustomerGenderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerGenderComboBoxActionPerformed

    }//GEN-LAST:event_CustomerGenderComboBoxActionPerformed

    private void CustomerLicenseNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerLicenseNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerLicenseNumberTextFieldActionPerformed

    private void ActionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionComboBoxActionPerformed
        this.currentAction = ActionComboBox.getSelectedItem().toString();
        ActionButton.setText(this.currentAction);
        resetAll();
        if (this.currentAction.equals("Update")) {
            PersonIDTextField.setEnabled(true);
            SelectButton.setEnabled(true);
            CustomerDOBDatePicker.setEnabled(false);
            CustomerLicenseNumberTextField.setEnabled(false);
            EmployeeDOBDatePicker.setEnabled(false);
            EmployeePhoneExtensionTextField.setEnabled(false);
            EmployeeUsernameTextField.setEnabled(false);
        } else if (this.currentAction.equals("Add")) {
            PersonIDTextField.setEnabled(false);
            SelectButton.setEnabled(false);
            CustomerDOBDatePicker.setEnabled(true);
            CustomerLicenseNumberTextField.setEnabled(true);
            EmployeeDOBDatePicker.setEnabled(true);
            EmployeePhoneExtensionTextField.setEnabled(true);
            EmployeeUsernameTextField.setEnabled(true);
        }
    }//GEN-LAST:event_ActionComboBoxActionPerformed

    private void ActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButtonActionPerformed
        if (this.currentAction.equals("Update")) {
            if (AddUpdatePersonTabbedPane.getSelectedIndex() == 0) {
                if (currentIDSelected == 0) {
                    JOptionPane.showMessageDialog(this, "Please select a customer with their ID.",
                    "No Customer Selected", JOptionPane.WARNING_MESSAGE);
                }
                for (Customer c : IndexFrame.db.CustomerList) {
                    if (currentIDSelected == c.getPersonID()) {
                        if (
                            CustomerNameTextField.getText().length() == 0
                            || CustomerGenderComboBox.getSelectedIndex() == 0
                            || CustomerAddressTextField.getText().length() == 0
                            || CustomerTelephoneTextField.getText().length() == 0
                            || CustomerLicenseNumberTextField.getText().length() == 0
                            || CustomerLicenseTypeComboBox.getSelectedIndex() == 0
                            || CustomerLicenseExpiryDatePicker.getDate() == null
                        ) {
                           JOptionPane.showMessageDialog(this, "Field cannot be left empty.",
                                    "Empty Field", JOptionPane.WARNING_MESSAGE);
                            break;
                        } else if (
                            CustomerNameTextField.getText().equals(c.getName())
                            && CustomerGenderComboBox.getSelectedItem().toString().equals(c.getGender())
                            && CustomerAddressTextField.getText().equals(c.getAddress())
                            && CustomerTelephoneTextField.getText().equals(c.getTelNumber())
                            && CustomerLicenseNumberTextField.getText().equals(c.getLicenseNumber()+"")
                            && LicenseType.valueOf(CustomerLicenseTypeComboBox.getSelectedItem()
                                .toString().toUpperCase()).equals(c.getLicenseType())
                            && IndexFrame.isSameDate(IndexFrame.CalendarNoHSM(CustomerLicenseExpiryDatePicker.getDate()),
                                IndexFrame.CalendarNoHSM(c.getLicenseExpiryDate()))
                        ) {
                            JOptionPane.showMessageDialog(this, "Please update customer information.",
                                    "Update Information", JOptionPane.WARNING_MESSAGE);
                            break;
                        } else if (CustomerLicenseExpiryDatePicker.getDate().before(new Date())) {
                            JOptionPane.showMessageDialog(this, "License must not be expired.",
                                    "Invalid License Expiry Date", JOptionPane.ERROR_MESSAGE);
                            break;
                        }
                        
                        c.setName(CustomerNameTextField.getText());
                        c.setGender(CustomerGenderComboBox.getSelectedItem().toString().toUpperCase().charAt(0));
                        c.setAddress(CustomerAddressTextField.getText());
                        c.setTelNumber(CustomerTelephoneTextField.getText());
                        c.setLicenseType(LicenseType.valueOf(CustomerLicenseTypeComboBox.getSelectedItem().toString().toUpperCase()));
                        c.setLicenseExpiryDate(CustomerLicenseExpiryDatePicker.getDate());
                        
                        JOptionPane.showMessageDialog(this, "Successfully updated customer " + c.getName() + "'s information.",
                                "Customer Info Updated", JOptionPane.INFORMATION_MESSAGE);
                        resetAll();
                    }
                    
                }
            } else if (AddUpdatePersonTabbedPane.getSelectedIndex() == 1) {
                if (currentIDSelected == 0) {
                    JOptionPane.showMessageDialog(this, "Please select a employee with their ID.",
                    "No Employee Selected", JOptionPane.WARNING_MESSAGE);
                }
                for (Employee e : IndexFrame.db.EmployeeList) {
                    if (currentIDSelected == e.getPersonID()) {
                        if (
                            EmployeeNameTextField.getText().equals(e.getName())
                            && EmployeeGenderComboBox.getSelectedItem().toString().equals(e.getGender())
                            && EmployeeAddressTextField.getText().equals(e.getAddress())
                            && EmployeeTelephoneTextField.getText().equals(e.getTelNumber())
                            && EmployeePhoneExtensionTextField.getText().equals(e.getPhoneExt())
                            && Role.valueOf(EmployeeRoleComboBox.getSelectedItem().toString().toUpperCase()).equals(e.getRole())
                            && EmployeePasswordTextField.getText().equals(e.getPassword())
                        ) {
                            JOptionPane.showMessageDialog(this, "Please update customer information.",
                                    "Update Information", JOptionPane.WARNING_MESSAGE);
                            break;
                        } else if (
                            EmployeeNameTextField.getText().length() == 0
                            || EmployeeGenderComboBox.getSelectedIndex() == 0
                            || EmployeeAddressTextField.getText().length() == 0
                            || EmployeeTelephoneTextField.getText().length() == 0
                            || EmployeePhoneExtensionTextField.getText().length() == 0
                            || EmployeeRoleComboBox.getSelectedIndex() == 0
                            || EmployeePasswordTextField.getText().length() == 0
                        ) {
                            JOptionPane.showMessageDialog(this, "Field cannot be left empty.",
                                    "Empty Field", JOptionPane.WARNING_MESSAGE);
                            break;
                        }
                        
                        e.setName(EmployeeNameTextField.getText());
                        e.setGender(EmployeeGenderComboBox.getSelectedItem().toString().toUpperCase().charAt(0));
                        e.setAddress(EmployeeAddressTextField.getText());
                        e.setTelNumber(EmployeeTelephoneTextField.getText());
                        e.setRole(Role.valueOf(EmployeeRoleComboBox.getSelectedItem().toString().toUpperCase()));
                        e.setPhoneExt(EmployeePhoneExtensionTextField.getText());
                        e.setPassword(EmployeePasswordTextField.getText());

                        JOptionPane.showMessageDialog(this, "Successfully updated employee " + e.getName() + "'s information.",
                                "EmployeeInfo Updated", JOptionPane.INFORMATION_MESSAGE);
                        resetAll();
                    }
                }
            }
        } else if (this.currentAction.equals("Add")) {
            if (AddUpdatePersonTabbedPane.getSelectedIndex() == 0 && validateCustomerData()) {
                int newCustomerID = IndexFrame.db.CustomerList.size() + 1;
                Customer newCustomer = new Customer(
                    newCustomerID,
                    CustomerNameTextField.getText(),
                    CustomerGenderComboBox.getSelectedItem().toString().charAt(0),
                    CustomerDOBDatePicker.getDate(),
                    CustomerAddressTextField.getText(),
                    CustomerTelephoneTextField.getText(),
                    Integer.parseInt(CustomerLicenseNumberTextField.getText()),
                    LicenseType.valueOf(CustomerLicenseTypeComboBox.getSelectedItem().toString().toUpperCase()),
                    CustomerLicenseExpiryDatePicker.getDate()
                );
                IndexFrame.db.CustomerList.add(newCustomer);
                
                JOptionPane.showMessageDialog(this, "Successfully added a new customer.",
                    "New Customer Added", JOptionPane.INFORMATION_MESSAGE);
                resetAll();
            } else if (AddUpdatePersonTabbedPane.getSelectedIndex() == 1 && validateEmployeeData()) {
                int newEmployeeID = IndexFrame.db.EmployeeList.size()+1;
                Employee newEmployee = new Employee(
                        newEmployeeID,
                        EmployeeNameTextField.getText(),
                        EmployeeGenderComboBox.getSelectedItem().toString().charAt(0),
                        EmployeeDOBDatePicker.getDate(),
                        EmployeeAddressTextField.getText(),
                        EmployeeTelephoneTextField.getText(),
                        EmployeePhoneExtensionTextField.getText(),
                        Role.valueOf(EmployeeRoleComboBox.getSelectedItem().toString().toUpperCase()),
                        EmployeeUsernameTextField.getText(),
                        EmployeePasswordTextField.getText()
                );
                IndexFrame.db.EmployeeList.add(newEmployee);
                JOptionPane.showMessageDialog(this, "Successfully added a new employee.",
                    "New Employee Added", JOptionPane.INFORMATION_MESSAGE);
                resetAll();
            }
        }
    }//GEN-LAST:event_ActionButtonActionPerformed

    private void CustomerLicenseTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerLicenseTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerLicenseTypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionButton;
    private javax.swing.JComboBox<String> ActionComboBox;
    private javax.swing.JTabbedPane AddUpdatePersonTabbedPane;
    private javax.swing.JTextField CustomerAddressTextField;
    private org.jdesktop.swingx.JXDatePicker CustomerDOBDatePicker;
    private javax.swing.JComboBox<String> CustomerGenderComboBox;
    private org.jdesktop.swingx.JXDatePicker CustomerLicenseExpiryDatePicker;
    private javax.swing.JTextField CustomerLicenseNumberTextField;
    private javax.swing.JComboBox<String> CustomerLicenseTypeComboBox;
    private javax.swing.JTextField CustomerNameTextField;
    private javax.swing.JPanel CustomerTab;
    private javax.swing.JTextField CustomerTelephoneTextField;
    private javax.swing.JTextField EmployeeAddressTextField;
    private org.jdesktop.swingx.JXDatePicker EmployeeDOBDatePicker;
    private javax.swing.JComboBox<String> EmployeeGenderComboBox;
    private javax.swing.JTextField EmployeeNameTextField;
    private javax.swing.JTextField EmployeePasswordTextField;
    private javax.swing.JTextField EmployeePhoneExtensionTextField;
    private javax.swing.JComboBox<String> EmployeeRoleComboBox;
    private javax.swing.JTextField EmployeeTelephoneTextField;
    private javax.swing.JTextField EmployeeUsernameTextField;
    private javax.swing.JTextField PersonIDTextField;
    private javax.swing.JButton SelectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
