/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeecustomermanagement;

import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author nepom
 */
public class IndexFrame extends javax.swing.JFrame {

    public static Database db = new Database();
    
    /**
     * Creates new form HomeFrame
     */
    public IndexFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeDesktopPane = new javax.swing.JDesktopPane();
        HomeFrameMenuBar = new javax.swing.JMenuBar();
        CRMMenu = new javax.swing.JMenu();
        ViewMenu = new javax.swing.JMenu();
        ViewRentersMenuItem = new javax.swing.JMenuItem();
        ViewPersonMenuItem = new javax.swing.JMenuItem();
        AddUpdateMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        setForeground(java.awt.Color.white);

        HomeDesktopPane.setBackground(new java.awt.Color(204, 204, 255));
        HomeDesktopPane.setName(""); // NOI18N

        javax.swing.GroupLayout HomeDesktopPaneLayout = new javax.swing.GroupLayout(HomeDesktopPane);
        HomeDesktopPane.setLayout(HomeDesktopPaneLayout);
        HomeDesktopPaneLayout.setHorizontalGroup(
            HomeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        HomeDesktopPaneLayout.setVerticalGroup(
            HomeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        CRMMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CRMMenu.setText("Customer & Employee Management");
        CRMMenu.setFont(new java.awt.Font("Verdana Pro Cond Semibold", 0, 12)); // NOI18N
        CRMMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CRMMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CRMMenu.setMargin(new java.awt.Insets(3, 10, 3, 10));
        CRMMenu.setPreferredSize(new java.awt.Dimension(200, 20));

        ViewMenu.setText("View");

        ViewRentersMenuItem.setText("View Renters");
        ViewRentersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRentersMenuItemActionPerformed(evt);
            }
        });
        ViewMenu.add(ViewRentersMenuItem);

        ViewPersonMenuItem.setText("View Person");
        ViewPersonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPersonMenuItemActionPerformed(evt);
            }
        });
        ViewMenu.add(ViewPersonMenuItem);

        CRMMenu.add(ViewMenu);

        AddUpdateMenuItem.setText("Add/Update Person");
        AddUpdateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUpdateMenuItemActionPerformed(evt);
            }
        });
        CRMMenu.add(AddUpdateMenuItem);

        HomeFrameMenuBar.add(CRMMenu);

        setJMenuBar(HomeFrameMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeDesktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddUpdateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        AddUpdatePersonIFrame addupd = new AddUpdatePersonIFrame();
        HomeDesktopPane.removeAll();
        HomeDesktopPane.add(addupd);
        addupd.setVisible(true);
    }

    private void ViewRentersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRentersMenuItemActionPerformed
        ViewRentersIFrame renterFrame = new ViewRentersIFrame();
        HomeDesktopPane.removeAll();
        HomeDesktopPane.add(renterFrame);
        renterFrame.setVisible(true);
    }//GEN-LAST:event_ViewRentersMenuItemActionPerformed

    private void ViewPersonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        ViewPersonIFrame personFrame = new ViewPersonIFrame();
        HomeDesktopPane.removeAll();
        HomeDesktopPane.add(personFrame);
        personFrame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IndexFrame().setVisible(true);
            }
        });
    }
    
    /* Check a string if it is a number */
    public static boolean isInt(String n) {
        try {
            Integer.parseInt(n);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    /* This function is to create a Calendar object from a Date object and
    trim its hours, seconds, and milliseconds */
    public static Calendar CalendarNoHSM(Date date) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.HOUR, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        return cal;
    }

    // Check both date
    public static boolean isSameDate(Calendar date1, Calendar date2) {
        return date1.get(Calendar.YEAR) == date2.get(Calendar.YEAR)
        && date1.get(Calendar.MONTH) == date2.get(Calendar.MONTH)
        && date1.get(Calendar.DATE) == date2.get(Calendar.DATE);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem AddUpdateMenuItem;
    private javax.swing.JMenu CRMMenu;
    private javax.swing.JDesktopPane HomeDesktopPane;
    private javax.swing.JMenuBar HomeFrameMenuBar;
    private javax.swing.JMenu ViewMenu;
    private javax.swing.JMenuItem ViewPersonMenuItem;
    private javax.swing.JMenuItem ViewRentersMenuItem;
    // End of variables declaration
}