package employeecustomermanagement;

import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author nepom
 */
public class ViewRentersIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewRentersIFrame
     */
    public ViewRentersIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        RenterTable = new javax.swing.JTable();
        FromDatePicker = new org.jdesktop.swingx.JXDatePicker();
        FromLabel = new javax.swing.JLabel();
        ToDatePicker = new org.jdesktop.swingx.JXDatePicker();
        ToLabel = new javax.swing.JLabel();
        SearchRenterButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("View Renters");
        setPreferredSize(new java.awt.Dimension(700, 360));

        RenterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Address", "Telephone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(RenterTable);

        FromDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromDatePickerActionPerformed(evt);
            }
        });

        FromLabel.setText("From:");

        ToDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToDatePickerActionPerformed(evt);
            }
        });

        ToLabel.setText("To:");

        SearchRenterButton.setText("Search");
        SearchRenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRenterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(FromLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FromDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchRenterButton)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromLabel)
                    .addComponent(FromDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToLabel)
                    .addComponent(ToDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchRenterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchRenterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRenterButtonActionPerformed

        DefaultTableModel model = (DefaultTableModel) RenterTable.getModel();
        model.setRowCount(0);

        Date fromDate = FromDatePicker.getDate();
        Date toDate = ToDatePicker.getDate();

        // Date cannot be empty
        if (fromDate == null || toDate == null) {
            JOptionPane.showMessageDialog(this, "Please select range of date.",
            "Empty Date", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // From date cannot be after the To date
        if (fromDate.after(toDate)) {
            JOptionPane.showMessageDialog(this, "Please input a valid range of date.",
            "Invalid Date", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Calendar startDate = IndexFrame.CalendarNoHSM(fromDate);
        Calendar endDate = IndexFrame.CalendarNoHSM(toDate);

        // Search rented cars
        while (!startDate.after(endDate)) {
            Date currentDate = startDate.getTime();

            for (RentedCar rentedCar : IndexFrame.db.CarRentedList) {
                Calendar rentedCal = IndexFrame.CalendarNoHSM(rentedCar.getDateRented());
                Calendar currentCal = IndexFrame.CalendarNoHSM(currentDate);

                // Compare year, month, and day only
                if (IndexFrame.isSameDate(rentedCal, currentCal)) {

                    Customer customer = rentedCar.getCustomer();
                    Object[] rowData = {
                        customer.getName(),
                        customer.getGender(),
                        customer.getAddress(),
                        customer.getTelNumber()
                    };
                    model.addRow(rowData);
                }
            }
            startDate.add(Calendar.DATE, 1);
        }

        // If no renters found
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No renters found.",
            "Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SearchRenterButtonActionPerformed

    private void FromDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromDatePickerActionPerformed

    private void ToDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToDatePickerActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker FromDatePicker;
    private javax.swing.JLabel FromLabel;
    private javax.swing.JTable RenterTable;
    private javax.swing.JButton SearchRenterButton;
    private org.jdesktop.swingx.JXDatePicker ToDatePicker;
    private javax.swing.JLabel ToLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
