package employeecustomermanagement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author nepom
 */
public class ViewPersonIFrame extends javax.swing.JInternalFrame {

    private DefaultTableModel customerTable;
    private DefaultTableModel employeeTable;

    /**
     * Creates new form ViewPersonIFrame
     */
    public ViewPersonIFrame() {
        initComponents();
        this.customerTable = (DefaultTableModel) ViewCustomerTable.getModel();
        this.employeeTable = (DefaultTableModel) ViewEmployeeTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PersonIDTextField = new javax.swing.JTextField();
        ViewByIDButton = new javax.swing.JButton();
        ViewAllButton = new javax.swing.JButton();
        ViewPersonTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ViewCustomerTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewEmployeeTable = new javax.swing.JTable();

        setTitle("View Person");
        setPreferredSize(new java.awt.Dimension(700, 360));

        jLabel2.setText("ID");

        PersonIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonIDTextFieldActionPerformed(evt);
            }
        });

        ViewByIDButton.setText("View by ID");
        ViewByIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewByIDButtonActionPerformed(evt);
            }
        });

        ViewAllButton.setText("View All");
        ViewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllButtonActionPerformed(evt);
            }
        });

        ViewPersonTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ViewPersonTabbedPaneStateChanged(evt);
            }
        });
        ViewPersonTabbedPane.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ViewPersonTabbedPanePropertyChange(evt);
            }
        });

        ViewCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerID", "Name", "Gender", "Date of Birth", "Address", "Telephone Number", "License Number", "License Type", "License Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ViewCustomerTable);

        ViewPersonTabbedPane.addTab("Customer", jScrollPane2);

        ViewEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Name", "Gender", "Date of Birth", "Address", "Telephone Number", "Phone Ext", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ViewEmployeeTable);

        ViewPersonTabbedPane.addTab("Staff", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewPersonTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PersonIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewByIDButton)
                .addGap(18, 18, 18)
                .addComponent(ViewAllButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PersonIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewByIDButton)
                    .addComponent(ViewAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewPersonTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void PersonIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonIDTextFieldActionPerformed

    private void ViewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllButtonActionPerformed
        PersonIDTextField.setText("");
        if (ViewPersonTabbedPane.getSelectedIndex() == 0) {
            customerTable.setRowCount(0);
            for (Customer c : IndexFrame.db.CustomerList) {
                Object[] cols = getCustomerInformation(c);
                customerTable.addRow(cols);
            }
            if (customerTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "List of customer is empty.",
                "No Customer Found", JOptionPane.WARNING_MESSAGE);
            }
        } else if (ViewPersonTabbedPane.getSelectedIndex() == 1) {
            employeeTable.setRowCount(0);
            for (Employee e : IndexFrame.db.EmployeeList) {
                Object[] cols = getEmployeeInformation(e);
                employeeTable.addRow(cols);
            }
            if (employeeTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "List of employee is empty.",
                "No Employee Found", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_ViewAllButtonActionPerformed

    private void ViewByIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewByIDButtonActionPerformed
        String personIDText = PersonIDTextField.getText();
        int personID;

        // Input Validation: ID cannot be empty
        if (personIDText.length() == 0) {
            JOptionPane.showMessageDialog(this, "Person ID cannot be empty.",
            "Empty ID Field", JOptionPane.ERROR_MESSAGE);
            PersonIDTextField.setText("");

        // Input Validation: ID cannot be any other characters except integer
        } else if (!IndexFrame.isInt(personIDText) || 0 > Integer.parseInt(personIDText)) {
            JOptionPane.showMessageDialog(this, "Please input a valid ID number.",
            "Invalid ID", JOptionPane.ERROR_MESSAGE);
            PersonIDTextField.setText("");

        // Proceed to put personID value if no error
        } else {
            personID = Integer.parseInt(personIDText);
            if (ViewPersonTabbedPane.getSelectedIndex() == 0) {
                customerTable.setRowCount(0);
                for (Customer c : IndexFrame.db.CustomerList) {
                    if (personID == c.getPersonID()) {
                        Object[] cols = getCustomerInformation(c);
                        customerTable.addRow(cols);
                    }
                }
                if (customerTable.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No customer found.",
                    "No Customer Found", JOptionPane.INFORMATION_MESSAGE);
                }
            } else if (ViewPersonTabbedPane.getSelectedIndex() == 1) {
                employeeTable.setRowCount(0);
                for (Employee e : IndexFrame.db.EmployeeList) {
                    if (personID == e.getPersonID()) {
                        Object[] cols = getEmployeeInformation(e);
                        employeeTable.addRow(cols);
                    }
                }
                if (employeeTable.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No employee found.",
                            "No Employee Found", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_ViewByIDButtonActionPerformed

    private void ViewPersonTabbedPanePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ViewPersonTabbedPanePropertyChange
        
    }//GEN-LAST:event_ViewPersonTabbedPanePropertyChange

    private void ViewPersonTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ViewPersonTabbedPaneStateChanged

    }//GEN-LAST:event_ViewPersonTabbedPaneStateChanged


    private Object[] getCustomerInformation(Customer c) {
        Object[] cData = {
            c.getPersonID(),
            c.getName(),
            c.getGender(),
            c.getDateOfBirth(),
            c.getAddress(),
            c.getTelNumber(),
            c.getLicenseNumber(),
            c.getLicenseType(),
            c.getLicenseExpiryDate()
        };
        return cData;
    }

    private Object[] getEmployeeInformation(Employee e) {
        Object[] eData = {
            e.getPersonID(),
            e.getName(),
            e.getGender(),
            e.getDateOfBirth(),
            e.getAddress(),
            e.getTelNumber(),
            e.getPhoneExt(),
            e.getRole()
        };
        return eData;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PersonIDTextField;
    private javax.swing.JButton ViewAllButton;
    private javax.swing.JButton ViewByIDButton;
    private javax.swing.JTable ViewCustomerTable;
    private javax.swing.JTable ViewEmployeeTable;
    private javax.swing.JTabbedPane ViewPersonTabbedPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
